/**
 * @file tpl_app_interrupts.c
 *
 * @section descr File description
 *
 * Generated functions related to interrupts.
 *
 * Generated from application blink
 * Automatically generated by goil on Sun Apr 11 21:45:11 2021
 * from root OIL file blink.oil
 *
 * @section infos File informations
 *
 * $$Date$$
 * $$Rev$$
 * $$Author$$
 * $$URL$$
 */

#include "tpl_compiler.h"
#include "tpl_cortex_definitions.h"
#include "tpl_os_interrupt_kernel.h"
#include "cmsis_wrapper.h"


#define OS_START_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * To disable the priority 3 interrupts, the corresponding ICER
 * are set
 */
FUNC(void, OS_CODE) tpl_disable_priority_3_interrupts(void)
{
  NVIC->ICER[0] = 0x780000;
}

/*=============================================================================
 * To enable the priority 3 interrupts, the corresponding ISER
 * are set
 */
FUNC(void, OS_CODE) tpl_enable_priority_3_interrupts(void)
{
  NVIC->ISER[0] = 0x780000;
}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Tables to access enable and disable functions according to the priority of
 * the ISR
 */
#define OS_START_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

CONST(tpl_enable_disable_func, OS_CONST) tpl_enable_table[1] = {
  tpl_enable_priority_3_interrupts
};

CONST(tpl_enable_disable_func, OS_CONST) tpl_disable_table[1] = {
  tpl_disable_priority_3_interrupts
};

#define OS_STOP_SEC_CONST_UNSPECIFIED
#include "tpl_memmap.h"

#define OS_START_SEC_CODE
#include "tpl_memmap.h"

/*=============================================================================
 * Initialize the priorities in the NVIC according to the priorities defined
 * in the OIL/ARXML file
 */
FUNC(void, OS_CODE) tpl_init_it_priority(void)
{
  /*
   * Init of ISR category 2 priorities
   */

  /* Init the priority of CAN1_RX1_IRQ */
  NVIC_SetPriority(CAN1_RX1_IRQ_Number, OS_ISR_PRIO_UNSHIFTED);
  /* Init the priority of CAN1_SCE_IRQ */
  NVIC_SetPriority(CAN1_SCE_IRQ_Number, OS_ISR_PRIO_UNSHIFTED);
  /* Init the priority of CAN1_RX0_IRQ */
  NVIC_SetPriority(CAN1_RX0_IRQ_Number, OS_ISR_PRIO_UNSHIFTED);
  /* Init the priority of CAN1_TX_IRQ */
  NVIC_SetPriority(CAN1_TX_IRQ_Number, OS_ISR_PRIO_UNSHIFTED);
}

/*=============================================================================
 * To disable the OS interrupts, the corresponding ICER
 * are set
 */
FUNC(void, OS_CODE) tpl_disable_os_interrupts(void)
{
  NVIC->ICER[0] = 0x780000;
}

/*=============================================================================
 * To enable the OS interrupts, the corresponding ISER
 * are set
 */
FUNC(void, OS_CODE) tpl_enable_os_interrupts(void)
{
  NVIC->ISER[0] = 0x780000;
}


#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/* End of file tpl_init_it_priority.c */
